<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17701" started-at="2016-05-09T13:22:40Z" finished-at="2016-05-09T13:22:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17701" started-at="2016-05-09T13:22:40Z" finished-at="2016-05-09T13:22:57Z">
      <class name="org.learning.startup.SimpleTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:org.learning.startup.SimpleTest@548a9f61]" name="beforeMethod" is-config="true" duration-ms="5412" started-at="2016-05-09T15:22:40Z" finished-at="2016-05-09T15:22:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testLoggedInWithPO()[pri:0, instance:org.learning.startup.SimpleTest@548a9f61]" name="testLoggedInWithPO" duration-ms="12027" started-at="2016-05-09T15:22:45Z" finished-at="2016-05-09T15:22:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[My Account Lable is displayed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: My Account Lable is displayed expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.learning.startup.SimpleTest.testLoggedInWithPO(SimpleTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoggedInWithPO -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:org.learning.startup.SimpleTest@548a9f61]" name="afterMethod" is-config="true" duration-ms="250" started-at="2016-05-09T15:22:57Z" finished-at="2016-05-09T15:22:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- org.learning.startup.SimpleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
